services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./backend   
    container_name: server_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /backend/node_modules   
    environment:
      - MONGO_URI=mongodb://mongo:27017/userDB
      - PORT=5000

  client:
    build: ./frontend   
    container_name: client_container
    ports:
      - "5173:5173"
    depends_on:
      - server
    stdin_open: true
    tty: true
    # volumes:
    #   - ./frontend:/app
    #   - /frontend/node_modules  

volumes:
  mongo_data:
