- name: Deploy Skillstack Web on VM2
  hosts: webserver
  become: yes
  vars:
    backend_port: 5000
    frontend_port: 3000
  tasks:

   
    - name: Pull backend image from DockerHub
      docker_image:
        name: geesara/skillstack-backend
        tag: latest
        source: pull
        force_source: true

  
    - name: Pull frontend image from DockerHub
      docker_image:
        name: geesara/skillstack-frontend
        tag: latest
        source: pull
        force_source: true

    - name: Run backend container
      docker_container:
        name: backend
        image: geesara/skillstack-backend:latest
        state: started
        restart_policy: always
        recreate: yes
        ports:
          - "{{ backend_port }}:{{ backend_port }}"
        env:
          MONGO_URI: "{{ mongo_uri }}"
          AWS_ACCESS_KEY: "{{ aws_access_key }}"
          AWS_SECRET_KEY: "{{ aws_secret_key }}"
          AWS_REGION: "{{ aws_region }}"
          S3_BUCKET: "{{ s3_bucket }}"
          NODE_ENV: "production"

 
    - name: Run frontend container
      docker_container:
        name: frontend
        image: geesara/skillstack-frontend:latest
        state: started
        restart_policy: always
        recreate: yes
        ports:
          - "{{ frontend_port }}:5173"
        env:
          VITE_BACKEND_URL: "http://{{ ansible_host }}:{{ backend_port }}"