- name: Deploy Skillstack Web on VM2
  hosts: webserver
  become: yes
  vars:
    backend_port: 5000
    frontend_port: 3000
  tasks:

    # 1️⃣ Pull latest backend image
    - name: Pull backend image from DockerHub
      docker_image:
        name: geesara/skillstack-backend
        tag: latest
        source: pull

    # 2️⃣ Pull latest frontend image
    - name: Pull frontend image from DockerHub
      docker_image:
        name: geesara/skillstack-frontend
        tag: latest
        source: pull

    # 3️⃣ Run backend container with MongoDB Atlas URI
    - name: Run backend container
      docker_container:
        name: backend
        image: geesara/skillstack-backend:latest
        state: started
        restart_policy: always
        ports:
          - "{{ backend_port }}:{{ backend_port }}"
        env:
          MONGO_URI: "{{ mongo_uri }}"   # <-- injected from Jenkins
          NODE_ENV: "production"

    # 4️⃣ Run frontend container pointing to backend dynamically
    - name: Run frontend container
      docker_container:
        name: frontend
        image: geesara/skillstack-frontend:latest
        state: started
        restart_policy: always
        ports:
          - "{{ frontend_port }}:5173"
        env:
          REACT_APP_BACKEND_URL: "http://{{ ansible_host }}:{{ backend_port }}"
